### ISSUE TITLE
Python exited with code 139

### ISSUE THREAD

**Issue by vsincholle** [kevin808/azure-function-pyodbc-MI#2]
Got this error: 
System.Private.CoreLib: Exception while executing function: Functions.HttpTrigger. System.Private.CoreLib: python3 exited with code 139 (0x8B). .

When code is placed outside of main, it works well but when inside main I got this issue.
I tried with several OS (Ubuntu, Debian) and several versions of Python (3?7, 3.8 and 3.9)
Still same issue.... need some help please

**Comment by kevin808** [comment]
The Python exit code 139 often indicates a "segmentation violation" or a "segfault". In other words, this equates to a read or write of a memory address that's not mapped in the process.
And when code is placed outside of main, the code would be executed even if the script were imported as a module.
Further investigation would need to review the code. It's a good idea to raise a support ticket to engage someone to help review it.

**Comment by vsincholle** [comment]
Here is the solution : The issue is due to pyodbc version, to work with Azure you should use that one on your virtual env: pyodbc==4.0.32 :)
