### ISSUE TITLE
Exception: Error: ('01000', "[01000] [unixODBC][Driver Manager]Can't open lib 'ODBC Driver 13 for SQL Server' : file not found (0) (SQLDriverConnect)")

### ISSUE THREAD

**Issue by alwaysandeep** [kevin808/azure-function-pyodbc-MI#3]
Hi @kevin808 
Thanks for the repo. I tried to follow the code to setup the azure function app to query from azure sql database. However I received driver not found error at pyodbc.connect. Do we also have to attach the drivers to Azure Function app?  

Exception: Error: ('01000', "[01000] [unixODBC][Driver Manager]Can't open lib 'ODBC Driver 13 for SQL Server' : file not found (0) (SQLDriverConnect)")

**Comment by joana-mendonca** [comment]
I'm having this same issue on a project I am building on my own. Please update me on the solution for this matter.

**Comment by kevin808** [comment]
@alwaysandeep It seems that you are using 'ODBC Driver 13 for SQL Server', where version 13 is not installed.
You may run "cat /etc/odbcinst.ini" to check the available drivers and update it in code accordingly.

**Comment by kevin808** [comment]
@J04N4 Please check comment above, if there is any question, you can raise a support ticket to get assistance to check it in detail.

**Comment by alwaysandeep** [comment]
thanks for getting back @kevin808 . Since Azure Functions are server less, It isn't possible to check drivers I think. Let me check with their support. Essentially I did not had this issue running on my machine, only Azure Functions seem to be the issue

**Comment by alwaysandeep** [comment]
@J04N4  I opened a support ticket, the link below. The engineer from azure says that its possible to make it happen in azure functions. I tried some of the references he suggested, but couldn't make it work. Didn't get a chance to debug more. Were you able to figure out the fix?


https://learn.microsoft.com/en-us/answers/questions/1153699/unable-to-query-azure-sql-database-from-azure-pyth

**Comment by joana-mendonca** [comment]
@alwaysandeep Changing the driver from 13 to 17 in my code was indeed the solution for me. It seems like the containers that run on the Consumption Plan for Function Apps (Linux-Python), come with the  ODBC Driver 17 for SQL Server installed by default. So changing my code to it fixed it (even if in my connection string in the db was ODBC Driver 13 for SQL Server. It established the connection).
